@startuml MD

skinparam classAttributeIconSize 0
hide methods
left to right direction

class App {

}

class Organization {
        - String nome
        - String NIF
}

class Collaborator {
        - String nome
        - String email
        - String password
}

class Freelancer {
        - String id
        - String name
        - String levelOfExpertise
        - String email
        - String NIF
        - String bankAccountIBAN
        - String address
        - String country
}

Collaborator                 "1" -- "*"      Freelancer                : creates >
Organization                 "1" -- "1"      Collaborator              : has >
App                          "1" -- "*"      Organization              : has >
App                          "1" -- "*"      Freelancer                : has >

@enduml