@startuml CD
skinparam classAttributeIconSize 0
top to bottom direction

class PaymentScheduler {
        - Integer dayMonth
        - LocalTime timeOfDay
        + create (Integer day, LoaclTime timeOfDay, Organization org)
        + scheduleNestMonth()
        - getNextDate()
}

class MakePaymentTask {
        + create(Organization org, PaymentScheduler scheduler)
        + run()
        - makePayments()
}


class Transaction {

}


class Organization {
        - String nome
        + getListTransaction()
}

class ListTransaction {
        removeUnpaidTransactions()
}

class App {
        + getRegistPayment()
}

class Freelancer {
        - String id
        - String name
        - String levelOfExpertise
        - String email
        - String NIF
        - String bankAccountIBAN
        - String address
        - String country
}

MakePaymentTask ..> Organization
MakePaymentTask ..> App
MakePaymentTask ..> RegistPayment
MakePaymentTask ..> Payment

PaymentScheduler ..> Timer
PaymentScheduler ..> MakePaymentTask

App "1" --> "1" RegistPayment : has
App "1" --> "1" RegistOrganization : has
Organization "1" --> "1" ListTransaction : has
Payment                      "1" --> "1,..."  Transaction               : knows
Payment                          ..>          EmailAPI
Transaction                      ..>          PaymentAPI
Payment                          ..>          MonetaryUnitConversionAPI
Transaction                  "*" --> "1"      Freelancer                : knows
Organization                 "1" --> "1"      PaymentScheduler          : has
Payment                      "*" --> "1"      Organization              : knows
ListTransaction              "1" --> "*"      Transaction               : has
App                          "1" --> "1"      MonetaryUnitConversionAPI : knows
RegistOrganization           "1" --> "*"      Organization              : has
App                          "1" --> "1"      EmailAPI                  : knows
App                          "1" --> "1"      PaymentAPI                : knows
RegistPayment                "1" --> "*"      Payment                   : has

@enduml