@startuml SD
autonumber
hide footbox

participant "scheduler\n:PaymentScheduler" as SC
participant "timer:\nTimer" as TIMER
participant "task:\nMakePaymentTask" as TASK
participant "org\n:Organization" as org
participant ":App" as app
participant "rp\n:RegistPayment" as rp
participant "trs\n:Transaction" as trs
participant ":PaymentAPI" as papi
participant "payment\n:Payment" as pay
participant "lt\n:ListTransactions" as lt
participant "completeTransactions\n:ListTransactions" as ct

[o-> SC : create(day, timeOfDay, org)
activate SC
        SC -> SC : resetTime(day, timeOfDay)
        SC -> SC : scheduleNextMonth()
loop
        activate SC
                SC -> TASK**  : create(org, scheduler)
                SC -> TIMER** : create()
                SC -> SC : date = getNextDate()
                SC ->TIMER: schedule(task, date)
        deactivate SC
deactivate SC
        activate TIMER
                note over SC,TIMER  : On the specified date and time
                TIMER->TASK:run()
                activate TASK
                        TASK->TASK: makePayments()
                        activate TASK
                                TASK -> org : lt = getListTransaction()
                                activate org
                                deactivate org
                                TASK -> app : rp = getRegistPayment()
                                activate app
                                deactivate app
                                TASK -> rp : makePayments(lt, org)
                                activate rp
                                        rp -> ct ** : create()
                                        loop for each transaction
                                                rp -> lt : trs = getTransaction(ID)
                                                activate lt
                                                deactivate lt
                                                rp -> trs : payment = makeBankTransfer(org)
                                                activate trs
                                                        trs -> trs: amount = getAmountToPay()
                                                        trs -> trs: IBAN = getFreelancerIBAN()
                                                        trs -> papi: payTo(amount, IBAN)
                                                        activate papi
                                                                papi -> pay ** : create(trs, org)
                                                        deactivate papi
                                                deactivate trs
                                                rp -> lt : remove(trs)
                                                activate lt
                                                deactivate lt
                                                rp -> ct : add(trs)
                                                activate ct
                                                deactivate ct
                                                rp -> rp : add(payment)
                                        end
                                        rp -> ct : emailAboutPayment()
                                        activate ct
                                        deactivate ct
                                deactivate rp
                        deactivate TASK
                        TASK -> SC : scheduleNextMonth()
                        activate SC
                deactivate TASK
        deactivate TIMER
end


@enduml