@startuml SSD
autonumber
actor "Manager or Collaborator" as MC
participant ":System" as S

activate MC
        MC -> S : stars the visualize of overall statistics about freelancers
        activate S
        S --> MC : shows the freelancers in the system that working in the same\n oganization of the user and requests the user to select which ones to include.
        deactivate S
        MC -> S : selects more than one freelancer
        activate S
        S --> MC : presents the information ( mean and the standard deviation of the delays;\n histogram to analyze the delays ; mean and the standard deviation of\n the payments made )
        deactivate S
deactivate MC
@enduml