@startuml SSD
autonumber
actor "Manager or Collaborator" as MC
participant ":System" as S

activate MC
        MC -> S : stars the visualize of overall statistics about task execution times
        activate S
        S --> MC : request sorting of the data (i.e.name or payment value)
        deactivate S
        MC -> S : enter the requested data
        activate S
        S --> MC : presents the information ( mean and the standard deviation of the delays,\n of each one and of all freelancers; histogram to analyze the delays of\n each one and all the freelancers working to the organization; mean and the \nstandard deviation of the payments made to each one of the freelancers).
        deactivate S
deactivate MC
@enduml