@startuml MD

skinparam classAttributeIconSize 0
hide methods
left to right direction

class Colaborator {
        - String nome
        - String email
        - String password
}

class Manager {
        - String nome
        - String email
        - String password
}

class Transaction {

}

class TaskExecutionDetails {
        - Date endDate
        - Integer delayInDays
        - String DescriptionQualityOfWork
}

class HistoricalTransactionFile {

}

class PaymentScheduler {
        - Integer dayMonth
        - LocalTime timeOfDay
}

class Organization {
        - String nome
}

class Task {
        - String id
        - String description
        - Integer durationInHours
        - Double costPerHourOfJuniorEur
        - String category
}

class App {

}

class Administrator {
        - String nome
        - String email
        - String password
}

class EmailScheduler {

}

class User {
        - String nome
        - String email
        - String password
}

class Freelancer {
        - String id
        - String name
        - String levelOfExpertise
        - String email
        - String NIF
        - String bankAccountIBAN
        - String address
        - String country
}

Colaborator                  "1" -- "*"      Payment                   : creates >
Colaborator                  "1" -- "*"      Task                      : creates >
Colaborator                  "1" -- "*"      Freelancer                : creates >
Colaborator                  "1" -- "*"      HistoricalTransactionFile : loads >
Colaborator                "0,1" -- "1"      User                      : acts as >
Manager                      "1" -- "0,1"    PaymentScheduler          : defines >
Manager                    "0,1" -- "1"      User                      : acts as >
Payment                      "*" -- "1,..."  Transaction               : registers >
Payment                      "*" -- "1"      EmailAPI                  : uses >
Payment                      "*" -- "1"      PaymentAPI                : uses >
Payment                      "*" -- "1"      MonetaryUnitConversionAPI : uses >
Transaction                  "1" -- "1"      Task                      : relative to >
Transaction                  "1" -- "1"      TaskExecutionDetails      : executed with >
Transaction                  "*" -- "1"      Freelancer                : to >
TaskExecutionDetails         "1" -- "1"      Task                      : refer to >
HistoricalTransactionFile    "1" -- "*"      Transaction               : records >
PaymentScheduler             "1" -- "*"      Payment                   : makes automatically >
Organization                 "1" -- "1,..."  Colaborator               : has >
Organization                 "1" -- "1"      Manager                   : has >
Organization                 "1" -- "1"      PaymentScheduler          : uses >
Organization                 "1" -- "*"      Payment                   : responsable by >
Task                         "*" -- "1"      Freelancer                : executed by >
App                          "1" -- "1"      MonetaryUnitConversionAPI : supports >
App                          "1" -- "*"      Organization              : has >
App                          "1" -- "1"      EmailAPI                  : supports >
App                          "1" -- "1"      PaymentAPI                : supports >
App                          "1" -- "*"      Transaction               : registers >
App                          "1" -- "*"      Administrator             : has >
App                          "1" -- "*"      Freelancer                : has >
App                          "1" -- "*"      Task                      : has >
App                          "1" -- "1"      EmailScheduler            : has >
EmailScheduler               "1" -- "1"      EmailAPI                  : uses >
Administrator                "1" -- "*"      Organization              : adds >
Administrator              "0,1" -- "1"      User                      : acts as >
EmailAPI                     "1" -- "*"      User                      : e-mails >
EmailAPI                     "1" -- "*"      Freelancer                : e-mails >

@enduml