@startuml SSD

autonumber
actor Collaborator as C

activate C
C -> ":System" : creating of a new task.
activate ":System"
":System" --> C : request the task data \n(i.e. id, description, durationInHours, costPerHourOfJuniorEur, category)
deactivate ":System"

C -> ":System" : enter the requested data
activate ":System"
":System" --> C : presents data and asks for confirmation
deactivate ":System"

C -> ":System" : confirms
activate ":System"
":System" --> C : successful operation
deactivate ":System"

deactivate C
@enduml
