@startuml
autonumber
actor Administrator as A

activate A
A -> ":System" : adding new organization
activate ":System"
":System" --> A : requests organization data (i.e. name),\n the data of one manager of that organization (i.e. name, email and password)\n and  the data of one collaborator of the same organization  (i.e. name, email and password)
deactivate ":System"

A -> ":System" : enter the requested data
activate ":System"
":System" --> A : presents data and asks for confirmation
deactivate ":System"

A -> ":System" : confirms
activate ":System"
":System" --> A : successful operation
deactivate ":System"

deactivate A
@enduml
